# Generated by Django 4.2 on 2025-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conturi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefon',
            field=models.CharField(max_length=15),
        ),
    ]
