# Generated by Django 4.2 on 2025-01-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
                ('descriere', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Judete',
            },
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
                ('descriere', models.TextField()),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatii', to='locatii.judet')),
            ],
            options={
                'verbose_name_plural': 'Locatii',
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
                ('descriere', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('predefinit', 'Predefinit'), ('personalizat', 'Personalizat')], default='predefinit', max_length=40)),
                ('locatii', models.ManyToManyField(related_name='tururi', to='locatii.locatie')),
            ],
            options={
                'verbose_name_plural': 'Tururi',
            },
        ),
        migrations.CreateModel(
            name='Oras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
                ('descriere', models.TextField()),
                ('judet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orase', to='locatii.judet')),
            ],
            options={
                'verbose_name_plural': 'Orase',
            },
        ),
        migrations.AddField(
            model_name='locatie',
            name='oras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locatii', to='locatii.oras'),
        ),
    ]
