# Generated by Django 4.2 on 2025-01-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0002_alter_locatie_descriere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tur',
            name='nume',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
