# Generated by Django 4.2 on 2025-01-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0003_alter_tur_nume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ghid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=128)),
                ('limbi', models.CharField(default='romana, engleza', max_length=256)),
                ('telefon', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ghizi',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(choices=[('autocar', 'Autocar'), ('masina', 'Masina'), ('bicicleta', 'Bicicleta'), ('mers', 'Mers pe jos'), ('tren', 'Tren ')], max_length=60)),
                ('descriere', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Mijloace de transport',
            },
        ),
        migrations.AddField(
            model_name='tur',
            name='durata',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tur',
            name='ghid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tururi', to='locatii.ghid'),
        ),
        migrations.AddField(
            model_name='tur',
            name='transport',
            field=models.ManyToManyField(related_name='tururi', to='locatii.transport'),
        ),
    ]
