# Generated by Django 4.2 on 2025-01-25 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0004_ghid_transport_tur_durata_tur_ghid_tur_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tur',
            name='transport',
        ),
        migrations.AddField(
            model_name='tur',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tururi', to='locatii.transport'),
        ),
    ]
