# Generated by Django 4.2 on 2025-01-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0005_remove_tur_transport_tur_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tur',
            name='ghid',
        ),
        migrations.RemoveField(
            model_name='tur',
            name='transport',
        ),
        migrations.AddField(
            model_name='tur',
            name='pachet',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tur',
            name='durata',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
