# Generated by Django 4.2 on 2025-01-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0006_remove_tur_ghid_remove_tur_transport_tur_pachet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tur',
            name='pret',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
