# Generated by Django 4.2 on 2025-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0007_tur_pret'),
    ]

    operations = [
        migrations.AddField(
            model_name='locatie',
            name='imagine_locatie',
            field=models.ImageField(blank=True, null=True, upload_to='imagini'),
        ),
    ]
