# Generated by Django 4.2 on 2025-01-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0008_locatie_imagine_locatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tur',
            name='imagine_tur',
            field=models.ImageField(blank=True, null=True, upload_to='imagini'),
        ),
    ]
