# Generated by Django 4.2 on 2025-01-31 13:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locatii', '0009_tur_imagine_tur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numar_persoane', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('data_inceput', models.DateField()),
                ('creata', models.DateField(auto_now_add=True)),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervare', to='locatii.tur')),
                ('utilizator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervare', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Rezervari',
            },
        ),
    ]
