# Generated by Django 4.2 on 2025-02-03 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locatii', '0010_rezervare'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervare',
            name='status',
            field=models.CharField(choices=[('in asteptare', 'In asteptare'), ('in procesare', 'In procesare'), ('confirmata', 'Confirmata')], default='in asteptare', max_length=40),
        ),
        migrations.AlterField(
            model_name='rezervare',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervari', to='locatii.tur'),
        ),
        migrations.AlterField(
            model_name='rezervare',
            name='utilizator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervari', to=settings.AUTH_USER_MODEL),
        ),
    ]
