# Generated by Django 4.2 on 2025-02-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0011_rezervare_status_alter_rezervare_tur_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ghid',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
