# Generated by Django 4.2 on 2025-02-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0012_delete_ghid_delete_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervare',
            name='suma',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tur',
            name='pret',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
