# Generated by Django 4.2 on 2025-02-04 12:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locatii', '0014_recenzie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recenzie',
            name='data_actualizarii',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recenzie',
            name='rating',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='recenzie',
            unique_together={('utilizator', 'tur')},
        ),
    ]
