# Generated by Django 4.2 on 2025-02-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locatii', '0015_recenzie_data_actualizarii_alter_recenzie_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recenzie',
        ),
    ]
