# Generated by Django 4.2 on 2025-02-06 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locatii', '0016_delete_recenzie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recenzie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scor', models.IntegerField()),
                ('comentariu', models.CharField(blank=True, max_length=250, null=True)),
                ('creata', models.DateTimeField(auto_now_add=True)),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to='locatii.tur')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recenzii', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recenzii',
            },
        ),
    ]
